from .shoot import *
from .kiss import *
from .virt import *
from .hug import *
from .poke import *
from .pat import *
from .smoke import *
from .sleep import *
from .slap import *
from .sad import *
from .nom import *
from .lick import *
from .hit import *
from .depression import *
from .dance import *
from .cry import *
from .hide import *
from .love import *
from .hand import *
from .onhands import *
from .tea import *
from .coffee import *
from .medal import *
from .init import *